### ISSUE TITLE
参考にしてます．

### ISSUE THREAD

**Issue by zukakosan** [k3nt0w/topic_model#1]
このコードで読み込んでいる
BOWs = np.load("./wikidata.npy")
のデータってどういう形式のものですか？

**Comment by k3nt0w** [comment]
返信が遅れて大変申し訳ございません．
`BOWs = np.load("./wikidata.npy")`で読み込んでいるバイナリデータは，  
文書ごとに単語の出現頻度をカウントしたものになっています．
語彙次元`V`に相当するものだと考えていただいて結構です．

**Comment by zukakosan** [comment]
ありがとうございます．
